//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Common;
    using System.Data.Entity.Core.EntityClient;
    using System.Configuration;

    public partial class dbEmployeeEntities : DbContext
    {
        public dbEmployeeEntities()
            : base("name=dbEmployeeEntities")
        {
            var originalConnectinoString = ConfigurationManager.ConnectionStrings["dbEmployeeEntities"].ConnectionString;
            var entityBulider = new EntityConnectionStringBuilder(originalConnectinoString);
            var factory = DbProviderFactories.GetFactory(entityBulider.Provider);
            var providerBulider = factory.CreateConnectionStringBuilder();

            providerBulider.ConnectionString = entityBulider.ProviderConnectionString;

            providerBulider.Add("password", "yzuim1092netdbA");//加入SQL密碼資料

            entityBulider.ProviderConnectionString = providerBulider.ToString();

            this.Database.Connection.ConnectionString = entityBulider.ProviderConnectionString;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TableDoctors1081649> TableDoctors1081649 { get; set; }
        public virtual DbSet<TablePatients1081649> TablePatients1081649 { get; set; }
        public virtual DbSet<TableToors1081649> TableToors1081649 { get; set; }
        public virtual DbSet<TableToorman1081649> TableToorman1081649 { get; set; }
    }
}
