//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableDoctors1081649
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableDoctors1081649()
        {
            this.TablePatients1081649 = new HashSet<TablePatients1081649>();
            this.TableToors1081649 = new HashSet<TableToors1081649>();
            this.TableToorman1081649 = new HashSet<TableToorman1081649>();
        }
    
        public int 負責醫生編號 { get; set; }
        public string 醫生姓名 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TablePatients1081649> TablePatients1081649 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableToors1081649> TableToors1081649 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableToorman1081649> TableToorman1081649 { get; set; }
    }
}
